### ISSUE TITLE
App Name, domain name and logo

### ISSUE THREAD

**Issue by oezeb** [oezeb/alum-market#6]
The project name currently is `Alum Market` - Alum stands for Alumni - and we don't have a logo yet. Because the app is meant to be used by current students only, not alumni, the name `Alum Market` might be misleading. We are thinking about changing the name to something else. 

If you have any ideas for a new name, please let us know! We are also looking for a logo for the app. If you have any ideas for a logo, please let us know as well!

When looking for the app name, please make sure that the domain name is available and affordable ;)

**Comment by krishills** [comment]
Great project! I also believe that naming it “Alum Market” could be misleading, given that the marketplace's primary purpose is for current students. I'd like to propose two alternative names:
First, “StudentConnect.store” is a name that I find appealing. Such a name should instill a sense of community among students, promoting trust.
Second, “StudSwap.store” is another excellent choice. The name combines “student” and “swap,” clearly indicating that the site is mainly for current students interested in swapping goods amongst themselves.
Furthermore, I've verified that these domain names are available on “https://www.domain.com.”
Regarding the logo, I recommend using silhouettes of students interacting, studying, or sharing resources to underscore the social aspect of the app. Additionally, you could consider incorporating an image of a well-known building or the school/campus's logo to signify its affiliation with the intended educational institution.

**Comment by oezeb** [comment]
Because we are not selling anything, the `.store` domain may not be suitable. I recommend using `.com`, `.net`, or `.market` instead.

For the logo, once we agree on the name, we can make a wordmarks logo. It will be easier, simpler.

**Comment by oezeb** [comment]
`StudentConnect` is too broad, it gives the feel of a social media. students are not swapping anything either on the platform so `StudSwap` also is not a good choice. 

After consideration, I think we can use `USTC Market` with the domain name `ustc.market`.
